import "./assets/css/style.css";
import { Montserrat } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Head from "./details/head";

const montserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          <article>
            <div className={`${montserrat.className} mx-32 `}>{children}</div>
          </article>
        </main>
        <Footer />
      </body>
    </html>
  );
}
